import enum


class BaseLogEvent(enum.Enum):
    """
    Base class for all log event enums.
    Used as a common type hint across schemas (e.g., event: BaseLogEvent).
    """
    pass


class AuthLog(BaseLogEvent):
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    JWT_VALIDATION_FAILED = "JWT_VALIDATION_FAILED"


class GatewayLog(BaseLogEvent):
    AI_REQUEST_RECEIVED = "AI_REQUEST_RECEIVED"
    AI_REQUEST_COLLISION = "AI_REQUEST_COLLISION"
    AI_QUOTA_EXHAUSTED = "AI_QUOTA_EXHAUSTED"


class ReservationLog(BaseLogEvent):
    AI_RESERVATION_CREATED = "AI_RESERVATION_CREATED"
    AI_RESERVATION_COMPLETED = "AI_RESERVATION_COMPLETED"
    AI_RESERVATION_FAILED = "AI_RESERVATION_FAILED"


class ServiceLog(BaseLogEvent):
    AI_SERVICE_STARTED = "AI_SERVICE_STARTED"
    AI_SERVICE_IN_PROCESSING = "AI_SERVICE_IN_PROCESSING"
    AI_SERVICE_COMPLETED = "AI_SERVICE_COMPLETED"
    AI_SERVICE_TERMINATED = "AI_SERVICE_TERMINATED"
    AI_SERVICE_FAILED = "AI_SERVICE_FAILED"
    AI_SERVICE_ENDED = "AI_SERVICE_ENDED"

    AI_MY_QUOTA_REACHED = "AI_MY_QUOTA_REACHED"
    EXITING_AI_SERVICE = "EXITING_AI_SERVICE"


class RepairLog(BaseLogEvent):
    AI_REPAIR_INITIALIZED = "AI_REPAIR_INITIALIZED"
    AI_REPAIR_INITIALIZATION_STOPPED = "AI_REPAIR_INITIALIZATION_STOPED"

    AI_REPAIR_STARTED = "AI_REPAIR_STARTED"
    AI_REPARI_IN_PROGRESS = "AI_REPARI_IN_PROGRESS"
    AI_REPAIR_PREMATURELY_ENDED = "AI_REPAIR_PREMATURELY_ENDED"
    AI_REPAIR_SUCCESS = "AI_REPAIR_SUCCESS"
    AI_REPAIR_FAILED = "AI_REPAIR_FAILED"


class ProviderLog(BaseLogEvent):
    AI_PROVIDER_REQUEST = "AI_PROVIDER_REQUEST"
    AI_PROVIDER_IN_PROCESSING = "AI_PROVIDER_IN_PROCESSING"
    AI_PROVIDER_SUCCESS = "AI_PROVIDER_SUCCESS"
    AI_PROVIDER_FAILURE = "AI_PROVIDER_FAILURE"


class DatabaseLog(BaseLogEvent):
    DB_COMMIT = "DB_COMMIT"
    DB_ROLLBACK = "DB_ROLLBACK"
    DB_ERROR = "DB_ERROR"


class ExceptionLog(BaseLogEvent):
    # General / Application
    APP_EXCEPTION = "APP_EXCEPTION"
    UNHANDLED_EXCEPTION = "UNHANDLED_EXCEPTION"

    # Services
    AI_SERVICE_EXCEPTION = "AI_SERVICE_EXCEPTION"
    POSTING_SERVICE_EXCEPTION = "POSTING_SERVICE_EXCEPTION"

    # Auth & Account
    LOGIN_EXCEPTION = "LOGIN_EXCEPTION"
    LOGOUT_EXCEPTION = "LOGOUT_EXCEPTION"
    LOGOUT_ALL_DEVICES_EXCEPTION = "LOGOUT_ALL_DEVICES_EXCEPTION"
    PASSWORD_CHANGE_EXCEPTION = "PASSWORD_CHANGE_EXCEPTION"
    USER_CREATION_EXCEPTION = "USER_CREATION_EXCEPTION"
    ACTIVE_SESSION_COUNT_EXCEPTION = "ACTIVE_SESSION_COUNT_EXCEPTION"
    REVOKATION_CURRENT_SESSION_EXCEPTION = "REVOKATION_CURRENT_SESSION_EXCEPTION"
    LIKE_EXCEPTION = "LIKE_EXCEPTION"

    # Document & RAG Pipeline Processing
    FILE_UPLADONG_EXCEPTION = "FILE_UPLADONG_EXCEPTION"
    VALIDATED_FILE_SAVING_EXCEPTION = "VALIDATED_FILE_SAVING_EXCEPTION"
    SAVING_VALIDATED_FILE_EXCEPTION = "SAVING_VALIDATED_FILE_EXCEPTION"
    PARSING_SAVED_FILE_EXCEPTION = "PARSING_SAVED_FILE_EXCEPTION"
    CHUNKING_PARSE_DOC_EXCEPTION = "CHUNKING_PARSE_DOC_EXCEPTION"
    EMBEDDING_CHUNKS_EXCEPTION = "EMBEDDING_CHUNKS_EXCEPTION"
    TOKENIZATION_EXCEPTION = "TOKENIZATION_EXCEPTION"
    MISSING_DOCUMENT_EXCEPTION = "MISSING_DOCUMENT_EXCEPTION"
    INVALID_TASK1_PAYLOAD_EXCEPTION = "INVALID_TASK1_PAYLOAD_EXCEPTION"
    INVALID_TASK2_PAYLOAD_EXCEPTION = "INVALID_TASK2_PAYLOAD_EXCEPTION"


class SecurityLog(BaseLogEvent):
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    INAPPROPRIATE_CONTENT_DETECTED = "INAPPROPRIATE_CONTENT_DETECTED"
    UNKNOWN_INPUT = "UNKNOWN_INPUT"
    EMPTY_INPUT = "EMPTY_INPUT"
    UNSUPPORTED_INPUT = "UNSUPPORTED_INPUT"


class PostingLogs(BaseLogEvent):
    # Service lifecycle
    POSTING_SERVICE_STARTED = "POSTING_SERVICE_STARTED"
    EXITING_POSTING_SERVICE = "EXITING_POSTING_SERVICE"

    # Posts
    FETCHING_POSTS = "FETCHING_POSTS"
    FETCHING_POST = "FETCHING_POST"
    CREATING_POST = "CREATING_POST"
    UPDATING_POST = "UPDATING_POST"
    DELETING_POST = "DELETING_POST"

    # Comments
    FETCHING_COMMENTS = "FETCHING_COMMENTS"
    CREATING_COMMENT = "CREATING_COMMENT"
    DELETING_COMMENT = "DELETING_COMMENT"

    # Validation / Authorization
    VALIDATING_REQUEST = "VALIDATING_REQUEST"
    AUTHORIZATION_CHECK = "AUTHORIZATION_CHECK"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"


class AuthLogs(BaseLogEvent):
    # Service lifecycle
    AUTH_SERVICE_STARTED = "AUTH_SERVICE_STARTED"
    EXITING_AUTH_SERVICE = "EXITING_AUTH_SERVICE"

    # Authentication
    AUTHENTICATING_USER = "AUTHENTICATING_USER"
    REGISTERING_USER = "REGISTERING_USER"
    VERIFYING_TOKEN = "VERIFYING_TOKEN"
    REFRESHING_TOKEN = "REFRESHING_TOKEN"
    LOGGING_OUT_USER = "LOGGING_OUT_USER"

    # Validation / Authorization
    VALIDATING_REQUEST = "VALIDATING_REQUEST"
    AUTHORIZATION_CHECK = "AUTHORIZATION_CHECK"
    VALIDATING_SESSION = "VALIDATING_SESSION"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    # Redis & Session Store
    CONNECTING_TO_REDIS = "CONNECTING_TO_REDIS"
    CACHING_JWT_SESSION = "CACHING_JWT_SESSION"
    CHECKING_JWT_SESSION = "CHECKING_JWT_SESSION"
    DELETING_JWT_SESSION = "DELETING_JWT_SESSION"

    # Session Management
    CREATING_SESSION = "CREATING_SESSION"
    SESSION_CREATED = "SESSION_CREATED"
    CHECKING_SESSION = "CHECKING_SESSION"
    SESSION_FOUND = "SESSION_FOUND"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    CHECKING_ALL_SESSIONS = "CHECKING_ALL_SESSIONS"
    SESSIONS_FOUND = "SESSIONS_FOUND"
    NO_SESSION_FOUND = "NO_SESSION_FOUND"
    DELETING_SESSION = "DELETING_SESSION"
    SESSION_DELETED = "SESSION_DELETED"
    SESSION_ALREADY_DELETED = "SESSION_ALREADY_DELETED"
    DELETING_ALL_SESSIONS = "DELETING_ALL_SESSIONS"
    ALL_SESSIONS_DELETED = "ALL_SESSIONS_DELETED"
    SESSIONS_ALREADY_DELETED = "SESSIONS_ALREADY_DELETED"
    COUNTING_ACTIVE_SESSIONS = "COUNTING_ACTIVE_SESSIONS"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"


class LikeLogs(BaseLogEvent):
    # Service lifecycle
    LIKE_SERVICE_STARTED = "LIKE_SERVICE_STARTED"
    EXITING_LIKE_SERVICE = "EXITING_LIKE_SERVICE"

    # Actions
    LIKING_POST = "LIKING_POST"
    UNLIKING_POST = "UNLIKING_POST"
    FETCHING_USER_LIKES = "FETCHING_USER_LIKES"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"


class UserLogs(BaseLogEvent):
    # Service lifecycle
    USER_SERVICE_STARTED = "USER_SERVICE_STARTED"
    EXITING_USER_SERVICE = "EXITING_USER_SERVICE"

    # CRUD
    FETCHING_USERS = "FETCHING_USERS"
    FETCHING_USER = "FETCHING_USER"
    CREATING_USER = "CREATING_USER"
    UPDATING_USER = "UPDATING_USER"
    DELETING_USER = "DELETING_USER"

    # Validation / Authorization
    VALIDATING_REQUEST = "VALIDATING_REQUEST"
    AUTHORIZATION_CHECK = "AUTHORIZATION_CHECK"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"
    UPDATING_DATABASE = "UPDATING_DATABASE"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"