import enum


class BaseLogEvent(enum.Enum):
    pass 


class AuthLog(BaseLogEvent):
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    JWT_VALIDATION_FAILED = "JWT_VALIDATION_FAILED"




class GatewayLog(BaseLogEvent):
    AI_REQUEST_RECEIVED = "AI_REQUEST_RECEIVED"
    AI_REQUEST_COLLISION = "AI_REQUEST_COLLISION"
    AI_QUOTA_EXHAUSTED = "AI_QUOTA_EXHAUSTED"




class ReservationLog(BaseLogEvent):
    AI_RESERVATION_CREATED = "AI_RESERVATION_CREATED"
    AI_RESERVATION_COMPLETED = "AI_RESERVATION_COMPLETED"
    AI_RESERVATION_FAILED = "AI_RESERVATION_FAILED"




class ServiceLog(BaseLogEvent):
    AI_SERVICE_STARTED = "AI_SERVICE_STARTED"
    AI_SERVICE_IN_PROCESSING = "AI_SERVICE_IN_PROCESSING"
    AI_SERVICE_COMPLETED = "AI_SERVICE_COMPLETED" 
    AI_SERVICE_TERMINATED = "AI_SERVICE_TERMINATED"
    AI_SERVICE_FAILED = "AI_SERVICE_FAILED" 
    AI_SERVICE_ENDED = "AI_SERVICE_ENDED" 

    AI_MY_QUOTA_REACHED = "AI_MY_QUOTA_REACHED" 
    EXITING_AI_SERVICE = "EXITING_AI_SERVICE" 



class RepairLog(BaseLogEvent):
    AI_REPAIR_INITIALIZED = "AI_REPAIR_INITIALIZED"
    AI_REPAIR_INITIALIZATION_STOPPED = "AI_REPAIR_INITIALIZATION_STOPED" 

    AI_REPAIR_STARTED = "AI_REPAIR_STARTED"
    AI_REPARI_IN_PROGRESS = "AI_REPARI_IN_PROGRESS"
    AI_REPAIR_PREMATURELY_ENDED = "AI_REPAIR_PREMATURELY_ENDED" 
    AI_REPAIR_SUCCESS = "AI_REPAIR_SUCCESS"
    AI_REPAIR_FAILED = "AI_REPAIR_FAILED"




class ProviderLog(BaseLogEvent):
    AI_PROVIDER_REQUEST = "AI_PROVIDER_REQUEST"
    AI_PROVIDER_IN_PROCESSING = "AI_PROVIDER_IN_PROCESSING"
    AI_PROVIDER_SUCCESS = "AI_PROVIDER_SUCCESS"
    AI_PROVIDER_FAILURE = "AI_PROVIDER_FAILURE" #then only when llm.inoke cause issue





class DatabaseLog(BaseLogEvent):
    DB_COMMIT = "DB_COMMIT"
    DB_ROLLBACK = "DB_ROLLBACK"
    DB_ERROR = "DB_ERROR"




class ExceptionLog(BaseLogEvent):
    APP_EXCEPTION = "APP_EXCEPTION"
    AI_SERVICE_EXCEPTION = "AI_SERVICE_EXCEPTION"
    POSTING_SERVICE_EXCEPTION = "POSTING_SERVICE_EXCEPTION"
    UNHANDLED_EXCEPTION = "UNHANDLED_EXCEPTION"
    LOGIN_EXCEPTION = "LOGIN_EXCEPTION"
    LIKE_EXCEPTION = "LIKE_EXCEPTION"
    USER_CREATION_EXCEPTION = "USER_CREATION_EXCEPTION"
    FILE_UPLADONG_EXCEPTION = "FILE_UPLADONG_EXCEPTION"




class SecurityLog(BaseLogEvent):
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    INAPPROPRIATE_CONTENT_DETECTED = "INAPPROPRIATE_CONTENT_DETECTED"
    UNKNOWN_INPUT = "UNKNOWN_INPUT"
    EMPTY_INPUT = "EMPTY_INPUT"
    UNSUPPORTED_INPUT = "UNSUPPORTED_INPUT"



class PostingLogs(BaseLogEvent):
    # Service lifecycle
    POSTING_SERVICE_STARTED = "POSTING_SERVICE_STARTED"
    EXITING_POSTING_SERVICE = "EXITING_POSTING_SERVICE"

    # Posts
    FETCHING_POSTS = "FETCHING_POSTS"
    FETCHING_POST = "FETCHING_POST"

    CREATING_POST = "CREATING_POST"
    UPDATING_POST = "UPDATING_POST"
    DELETING_POST = "DELETING_POST"

    # Comments
    FETCHING_COMMENTS = "FETCHING_COMMENTS"
    CREATING_COMMENT = "CREATING_COMMENT"
    DELETING_COMMENT = "DELETING_COMMENT"

    # Validation / Authorization
    VALIDATING_REQUEST = "VALIDATING_REQUEST"
    AUTHORIZATION_CHECK = "AUTHORIZATION_CHECK"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"


class AuthLogs(BaseLogEvent):
    # Service lifecycle
    AUTH_SERVICE_STARTED = "AUTH_SERVICE_STARTED"
    EXITING_AUTH_SERVICE = "EXITING_AUTH_SERVICE"

    # Authentication
    AUTHENTICATING_USER = "AUTHENTICATING_USER"
    REGISTERING_USER = "REGISTERING_USER"
    VERIFYING_TOKEN = "VERIFYING_TOKEN"
    REFRESHING_TOKEN = "REFRESHING_TOKEN"

    # Validation / Authorization
    VALIDATING_REQUEST = "VALIDATING_REQUEST"
    AUTHORIZATION_CHECK = "AUTHORIZATION_CHECK"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"


class LikeLogs(BaseLogEvent):
    LIKE_SERVICE_STARTED = "LIKE_SERVICE_STARTED"

    LIKING_POST = "LIKING_POST"
    UNLIKING_POST = "UNLIKING_POST"
    FETCHING_USER_LIKES = "FETCHING_USER_LIKES"

    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"

    EXITING_LIKE_SERVICE = "EXITING_LIKE_SERVICE"


class UserLogs(BaseLogEvent):

    # Service lifecycle
    USER_SERVICE_STARTED = "USER_SERVICE_STARTED"

    # CRUD
    FETCHING_USERS = "FETCHING_USERS"
    FETCHING_USER = "FETCHING_USER"
    CREATING_USER = "CREATING_USER"
    UPDATING_USER = "UPDATING_USER"
    DELETING_USER = "DELETING_USER"

    # Validation / Authorization
    VALIDATING_REQUEST = "VALIDATING_REQUEST"
    AUTHORIZATION_CHECK = "AUTHORIZATION_CHECK"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"

    # Service lifecycle
    EXITING_USER_SERVICE = "EXITING_USER_SERVICE"